[project]
name = "silver-enigma"
version = "0.1.0"
description = "B2B order engine with stock control and fulfillment traceability for supplier → warehouse → store distribution chains."
authors = [
    {name = "Johann Gaviria"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.136.0,<0.137.0)",
    "uvicorn (>=0.44.0,<0.45.0)",
    "pydantic-settings (>=2.14.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "pytest-dotenv (>=0.5.2,<0.6.0)",
    "structlog (>=25.5.0,<26.0.0)",
    "sqlalchemy (>=2.0.49,<3.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "redis (>=7.4.0,<8.0.0)",
    "alembic (>=1.18.4,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "ruff (>=0.15.11,<0.16.0)",
    "mypy (>=1.20.1,<2.0.0)",
    "pre-commit (>=4.5.1,<5.0.0)"
]

[tool.poetry]
package-mode = false

# =========================
# PYTEST CONFIG
# =========================

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.coverage.run]
omit = ["*/alembic/*", "*/conftest.py"]

[tool.coverage.report]
show_missing = true
skip_covered = false

# =========================
# RUFF CONFIG
# =========================

[tool.ruff]
target-version = "py312"
line-length = 88
fix = true

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "alembic",
    "build",
    "dist"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "UP",
    "B",
    "C4",
    "D",
]

ignore = [
    "E501",
    "B008",
]

[tool.ruff.lint.isort]
known-first-party = ["silver_enigma"]
case-sensitive = true
force-wrap-aliases = true
split-on-trailing-comma = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
"tests/*" = ["D100", "D101", "D102", "D103", "D104", "D105", "D106"]
"alembic/*" = ["D100", "D101", "D102", "D103", "D104"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

# =========================
# MYPY CONFIG
# =========================

[tool.mypy]
python_version = "3.12"

warn_unused_configs = true
warn_unused_ignores = false

strict_optional = true
check_untyped_defs = true

disallow_untyped_defs = true
disallow_untyped_calls = false

ignore_missing_imports = false

exclude = [
    "migrations/",
]

[[tool.mypy.overrides]]
module = [
    "pydantic.*",
    "pydantic_settings.*"
]
ignore_errors = true

#[[tool.mypy.overrides]]
#module = [
#    "tests.e2e.*",
#    "tests.integration.*",
#    "tests.unit.*"
#]
#disallow_untyped_defs = false
