"""rename available_stock to reserved_stock in stocks.

Revision details for database migration.

Revision ID: 0564830e2231
Revises: c72d201f9437
Create Date: 2026-06-11 23:50:44.557230
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0564830e2231'
down_revision: Union[str, None] = 'c72d201f9437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('reserved_stock', sa.Integer(), nullable=False))
    op.drop_column('stocks', 'available_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('available_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('stocks', 'reserved_stock')
    # ### end Alembic commands ###
