"""add_orders_status_history_table.

Revision details for database migration.

Revision ID: ab1d6aa18b9f
Revises: 3de2cca6eb92
Create Date: 2026-06-12 13:45:05.965695
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1d6aa18b9f'
down_revision: Union[str, None] = '3de2cca6eb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_status_history',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('changed_by_role', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status_history_changed_by'), 'orders_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_orders_status_history_changed_by_role'), 'orders_status_history', ['changed_by_role'], unique=False)
    op.create_index(op.f('ix_orders_status_history_created_at'), 'orders_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status_history_id'), 'orders_status_history', ['id'], unique=True)
    op.create_index(op.f('ix_orders_status_history_new_status'), 'orders_status_history', ['new_status'], unique=False)
    op.create_index(op.f('ix_orders_status_history_order_id'), 'orders_status_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_status_history_previous_status'), 'orders_status_history', ['previous_status'], unique=False)
    op.create_index(op.f('ix_orders_status_history_updated_at'), 'orders_status_history', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status_history_updated_at'), table_name='orders_status_history')
    op.drop_index(op.f('ix_orders_status_history_previous_status'), table_name='orders_status_history')
    op.drop_index(op.f('ix_orders_status_history_order_id'), table_name='orders_status_history')
    op.drop_index(op.f('ix_orders_status_history_new_status'), table_name='orders_status_history')
    op.drop_index(op.f('ix_orders_status_history_id'), table_name='orders_status_history')
    op.drop_index(op.f('ix_orders_status_history_created_at'), table_name='orders_status_history')
    op.drop_index(op.f('ix_orders_status_history_changed_by_role'), table_name='orders_status_history')
    op.drop_index(op.f('ix_orders_status_history_changed_by'), table_name='orders_status_history')
    op.drop_table('orders_status_history')
    # ### end Alembic commands ###
