"""remove_warehouse_id_in_orders_table.

Revision details for database migration.

Revision ID: abd86be52206
Revises: ab1d6aa18b9f
Create Date: 2026-06-17 16:38:14.113318
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd86be52206'
down_revision: Union[str, None] = 'ab1d6aa18b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_warehouse_id'), table_name='orders')
    op.drop_column('orders', 'warehouse_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_orders_warehouse_id'), 'orders', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###
