"""add_inventory_allocation_table.

Revision details for database migration.

Revision ID: e17c7cd0f523
Revises: abd86be52206
Create Date: 2026-06-20 13:59:46.780249
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17c7cd0f523'
down_revision: Union[str, None] = 'abd86be52206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_allocations',
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_allocations_created_at'), 'inventory_allocations', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_allocations_id'), 'inventory_allocations', ['id'], unique=True)
    op.create_index(op.f('ix_inventory_allocations_order_item_id'), 'inventory_allocations', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_allocations_updated_at'), 'inventory_allocations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_inventory_allocations_warehouse_id'), 'inventory_allocations', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_allocations_warehouse_id'), table_name='inventory_allocations')
    op.drop_index(op.f('ix_inventory_allocations_updated_at'), table_name='inventory_allocations')
    op.drop_index(op.f('ix_inventory_allocations_order_item_id'), table_name='inventory_allocations')
    op.drop_index(op.f('ix_inventory_allocations_id'), table_name='inventory_allocations')
    op.drop_index(op.f('ix_inventory_allocations_created_at'), table_name='inventory_allocations')
    op.drop_table('inventory_allocations')
    # ### end Alembic commands ###
